Task#12. Spring Batch
anafalin/2024-09-otus-spring-lazarenko pull request #13
Opened 2024-12-23 20:27 UTC by anafalin

Реализовано приложение по миграции данных из реляционной базы данных в NoSQL БД.

В качестве тестового запуска приложение было запущено с параметром -Xms500m.
В PostgreSQL в таблицах базы данных приложения "Библиотека" было создано:
* 1000 записей в таблице "авторы"
* 100 записей в таблице "жанры"
* 1000000 записей в таблице "книги"
* 20000 записей в таблице "комментарии"

Выполнение программы:
![изображение](https://github.com/user-attachments/assets/b9eb0c40-2d72-437a-9f73-4768bc5cbf79)

И загрузка памяти в процессе выполнения:
![изображение](https://github.com/user-attachments/assets/f65a55b5-8683-4666-87c9-b2568ecc04f0)

2024-12-25 13:41 UTC, VladimirMagerov requested changes

2024-12-25 13:41 UTC, VladimirMagerov commented on hw12/src/main/resources/application.yaml
> +spring:
Структура таблиц в БД должна создаваться автоматически через миграцию (как в предыдущих ДЗ), пожалуйста, добавьте это и сюда тоже)

2024-12-25 20:38 UTC, anafalin commented on hw12/src/main/resources/application.yaml
> +spring:
Сделано!)

2024-12-27 14:13 UTC, VladimirMagerov approved these changes

2024-12-28 16:56 UTC, merged