Task #13. Spring Security: authentication mechanism
anafalin/2024-09-otus-spring-lazarenko pull request #14
Opened 2024-12-29 20:29 UTC by anafalin

Добавлен механизм аутентификации - форма входа, выхода, и доступ к эндпоинтам приложения только для авторизованных пользователей, кроме начальной страницы  - доступна всем пользователям, как авторизованным, так и не авторизованным.

2025-01-10 07:26 UTC, VladimirMagerov requested changes

2025-01-10 07:26 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/security/SecurityUser.java
> +
Лишние пустые строки

2025-01-10 07:26 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/security/SecurityUser.java
> +public class SecurityUser implements UserDetails {
Была какая-то причина делать отдельные классы `SecurityUser` и `UserApp`? Вроде как они вполне могут быть просто одной общей сущностью `User`

2025-01-10 07:26 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/config/SecurityConfig.java
> +                        .requestMatchers("/home").authenticated()
Получается, защищена только главная страница? А как же все эндпоинты по управлению книгами и комментариями? В данный момент в принципе нельзя ни получить список книг, ни что-либо с ними сделать (по какой-то причине это не работает), это надо исправить и дополнительно защитить через конфигурацию - например, что все действия в библиотеке с книгами и комментариями могут делать только те, кто аутентифицирован.

2025-01-10 09:30 UTC, anafalin commented on hw13/src/main/java/ru/otus/hw/security/SecurityUser.java
> +public class SecurityUser implements UserDetails {
Ну как же... Я руководствовалась принципом разделения ответственности (Single Responsibility Principle)

2025-01-10 09:34 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/security/SecurityUser.java
> +public class SecurityUser implements UserDetails {
А какие именно ответственности тут разделены?

2025-01-10 09:48 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/security/SecurityUser.java
> +public class SecurityUser implements UserDetails {
Просто в конретной данной реализации никакой разницы между ними я сейчас не увидел, так как никакой личной и контактной информации у UserApp нет. Но если это было с делано с таким подходом - пусть будет)

2025-01-11 09:28 UTC, anafalin commented on hw13/src/main/java/ru/otus/hw/config/SecurityConfig.java
> +                        .requestMatchers("/home").authenticated()
Почему не работает?! Тут я оставила возможность всем зарегистрированным пользователям что-либо сделать с ресурсом. В бд уже есть три пользователя. Вот сейчас зашла под user_1 c паролем user1 и мне стало доступно все страницы и операции с книгами и т.д.
А не авторизованный пользователь может только главную страницу лицезреть, да.

2025-01-11 09:29 UTC, anafalin commented on hw13/src/main/java/ru/otus/hw/config/SecurityConfig.java
> +                        .requestMatchers("/home").authenticated()
Но сейчас сделаю более приближенное к реальности... Разделю возможности админа и пользователей.

2025-01-11 09:41 UTC, VladimirMagerov commented on hw13/src/main/java/ru/otus/hw/config/SecurityConfig.java
> +                        .requestMatchers("/home").authenticated()
Я понял в чём дело - у меня по причине 200% масштабирования браузер не отображались кнопки для работы с книгами, попытки вручную перейти на страничку с книгами тоже были неудачны в момент проверки. Сейчас перепроверил ещё раз - всё и правда работает)
В этом задании не надо разделять админа и пользователя - это должно быть в следующем.
Просто верните задание на проверку)

2025-01-11 10:09 UTC, anafalin commented on hw13/src/main/java/ru/otus/hw/config/SecurityConfig.java
> +                        .requestMatchers("/home").authenticated()
Да, с выпадающей менюшкой была проблема. Устранила и ее.

Хорошо:)

2025-01-14 17:13 UTC, VladimirMagerov approved these changes

2025-01-14 19:58 UTC, merged