Task #5. Библиотека (Spring JDBC)
anafalin/2024-09-otus-spring-lazarenko pull request #5
Opened 2024-11-06 21:05 UTC by anafalin

Используемые технологии для решения: 
* Spring JDBC,
* H2 database
* Liquibase 

Настроена миграция базы данных, созданы скрипты для создания таблиц и загрузки начальных(тестовых данных.)
Созданы entities, services для реализации СRUD операций для книг, read для авторов и жанров.
Настроен spring shell для работы с приложением.

Для методов репозитория книг написаны интеграционные тесты с помощью @JdbcTest  и встроенной БД. Загрузка тестовых данных осуществляется через скрипты schema.sql и data.sql.

2024-11-07 20:37 UTC, VladimirMagerov requested changes

2024-11-07 20:37 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcGenreRepository.java
> +                "select id, name from generes where id =: ids", params, Genre.class);
`genres` и `id in (:ids)`

2024-11-07 20:37 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcGenreRepository.java
> +                "select id, name from generes where id =: ids", params, Genre.class);
Плюсом к этому queryForList предназначен дляя получения значений одной колонки, а вы тут пытаетесь получить сразу две (https://stackoverflow.com/questions/33008205/incorrectresultsetcolumncountexception-incorrect-column-count-expected-1-actu) - соответственно, ошибка. (можно проверить просто попыткой добавить книгу)

2024-11-07 20:37 UTC, VladimirMagerov commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcBookRepository.java
> +    public List<Book> findAll() {
Предлагаю попробовать достать все данные одним запросом, а не тремя разными, и распарсить тоже одним проходом по результатам (а не "склеивать" самим результаты трёх отдельных запросов)

2024-11-08 17:40 UTC, anafalin commented on hw05/src/main/java/ru/otus/hw/repositories/JdbcGenreRepository.java
> +                "select id, name from generes where id =: ids", params, Genre.class);
Исправила. Теперь оценила значимость тестов. :)

2024-11-12 16:14 UTC, anafalin commented
@VladimirMagerov а можно Вас в телеграмие найти? 🙏🫣

2024-11-14 10:02 UTC, merged