Task #6. Библиотека (Hibrnate, JPA, ORM)
anafalin/2024-09-otus-spring-lazarenko pull request #6
Opened 2024-11-17 21:00 UTC by anafalin

Приложение библиотека переписана с Spring JDBC на ORM.

2024-11-20 13:45 UTC, VladimirMagerov requested changes

2024-11-20 13:45 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/repositories/JpaAuthorRepository.java
> +    @Transactional(readOnly = true)
`@Transactional` ставится _**только**_ над методами сервисов, не репозиториев

2024-11-20 13:45 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/commands/BookCommands.java
> +    public String findAllBooks() {
Ошибка при попытке получить все книги:
![image](https://github.com/user-attachments/assets/ab3b651a-0204-44af-9d61-721f4074143a)

2024-11-20 13:45 UTC, VladimirMagerov commented on hw06/src/main/java/ru/otus/hw/commands/BookCommands.java
> +    public String findAllBooks() {
Аналогично и с получением книги по ID, с получением комментариев по ID или по ID книги

2024-11-20 13:45 UTC, VladimirMagerov commented on hw06/src/test/java/ru/otus/hw/services/BookServiceImplTest.java
> +public class BookServiceImplTest {
Не покрыты negative сценарии, при которых выбрасываются исключения

2024-11-20 13:45 UTC, VladimirMagerov commented on hw06/src/test/java/ru/otus/hw/services/CommentServiceImplTest.java
> +public class CommentServiceImplTest {
Не покрыты negative сценарии, при которых выбрасываются исключения

2024-11-20 19:37 UTC, anafalin commented on hw06/src/main/java/ru/otus/hw/commands/BookCommands.java
> +    public String findAllBooks() {
исправлено путем введения dto

2024-11-20 19:37 UTC, anafalin commented on hw06/src/test/java/ru/otus/hw/services/BookServiceImplTest.java
> +public class BookServiceImplTest {
добавлены тесты на покрытие всех методов сервиса

2024-11-22 17:18 UTC, VladimirMagerov approved these changes

2024-11-22 21:38 UTC, merged